---
title: "Simple R Markdown Notebook"
author: "Lincoln Mullen"
---

### What is this?

If you use [R Markdown](http://rmarkdown.rstudio.com/) for data analysis projects, you might like to put your HTML reports on the web for people to look at. It would be nice if those pages were closely tied to your GitHub repository, but HTML pages render as code on GitHub proper. So this repository is a template for making a GitHub pages version of your analysis. Not that you have to use GitHub pages: you could just as easily rsync your HTML files anywhere else that you want.

For example, here is the table of contents for rendered versions of every R Markdown document in this repository.

### Table of contents

```{r echo=FALSE, results='asis'}
rmd <- Sys.glob("*.Rmd")
rmd <- rmd[rmd != "index.Rmd"]
html <- sub(".Rmd", ".html", rmd)
lines <- lapply(rmd, readLines)
yaml <- lapply(lines, rmarkdown:::parse_yaml_front_matter)
cat("<ul>")
for (i in seq_along(rmd)) {
  cat(paste0("<li><a href='", html[i], "'>", yaml[[i]]$title, "</a><br/>",
             "<code>", rmd[i], "</code>", "</li>"))
}
cat("</ul>")
```

### What does this do?

As little as possible. The aim is to be very lightweight. But it does do this:

1. Includes an index page (you're looking at it) with a table of contents for every `.Rmd` file in the root directory of your project.
2. Inserts a navigation header into each rendered HTML file.
4. Sets some shared options for HTML documents rendered from R Markdown.
5. Contains a basic Makefile to render all the documents.
  
Don't forget to commit the HTML files that you generate. You can then configure GitHub to create a web page from the master branch, as [explained here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/).

See the [GitHub repository](https://github.com/lmullen/rmd-notebook) for the source. See the [R Markdown documentation](http://rmarkdown.rstudio.com/) if you want to do more.
